### ISSUE TITLE
NullPointerException in PhotoView attacher with version 1.2.7

### ISSUE THREAD

**Issue by hamberluo** [chrisbanes/PhotoView#393]
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean uk.co.senab.photoview.PhotoViewAttacher.setDisplayMatrix(android.graphics.Matrix)' on a null object reference
       at uk.co.senab.photoview.PhotoView.setDisplayMatrix(PhotoView.java:98)
```

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void uk.co.senab.photoview.PhotoViewAttacher.setScaleLevels(float, float, float)' on a null object reference
       at uk.co.senab.photoview.PhotoView.setScaleLevels(PhotoView.java:148)
```

**Comment by Jawnnypoo** [comment]
Sounds like your attacher has been set to null and that you are still using a view that has been removed from the window. Can you recreate this with the sample app?

**Comment by hamberluo** [comment]
@Jawnnypoo mAttacher in PhotoView is set to null in onDetachedFromWindow with v1.2.7 and v1.3.0, but it is not set to null with v1.2.6.
This np crash did not occurs with v1.2.6

**Comment by Jawnnypoo** [comment]
I understand this, and it was done to prevent memory leaks with the attacher holding a reference to the imageview and causing entire activities to leak. I am wondering how you are recreating this issue, since when `onDetachFromWindow` is called, the view should be getting destroyed anyhow and the attacher should not be relevant or referenced anymore. Is there a code snippet you can paste to show behavior?

**Comment by hamberluo** [comment]
I use `PhotoView` with `ViewPager`. When `PhotoView` detach from window I need to adjust its' image size. Can this be helpful? Maybe I need to refactor my code to fix this problem. Thank you.

**Comment by Jawnnypoo** [comment]
Yeah, this is a sign that the code you are using is leaking memory if the attacher is being used after the view is detached, so it is not an issue for this library.
