### ISSUE TITLE
Error inflating class com.github.chrisbanes.photoview.PhotoView

### ISSUE THREAD

**Issue by akshayvinchurkar** [chrisbanes/PhotoView#490]

**Comment by Jawnnypoo** [comment]
I'll reopen if you add more details than that.

**Comment by yterletskyi** [comment]
I reproduce this too 
`android.view.InflateException: Binary XML file line #6: Binary XML file line #6: Error inflating class com.github.chrisbanes.photoview.PhotoView`

Here is my layout file:
`<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:background="@android:color/black">

    <com.github.chrisbanes.photoview.PhotoView
        android:id="@+id/img_photo_single"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_centerInParent="true"
        android:layout_marginBottom="4dp"
        android:layout_marginTop="4dp"
        android:scaleType="fitCenter"
        android:src="@mipmap/ic_launcher"/>

    <ProgressBar
        android:id="@+id/trw"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_centerInParent="true"
        android:visibility="gone"/>

</RelativeLayout>
`

**Comment by Sandrichka22** [comment]
I am also getting the following error:

02-05 23:23:15.882 E/AndroidRuntime(26682): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.test.app/com.test.app.TestActivity}: android.view.InflateException: Binary XML file line #31: Binary XML file line #31: Error inflating class com.github.chrisbanes.photoview.PhotoView
02-05 23:23:15.882 E/AndroidRuntime(26682): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2984)
02-05 23:23:15.882 E/AndroidRuntime(26682): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3045)
02-05 23:23:15.882 E/AndroidRuntime(26682): 	at android.app.ActivityThread.-wrap14(ActivityThread.java)
02-05 23:23:15.882 E/AndroidRuntime(26682): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1642)
02-05 23:23:15.882 E/AndroidRuntime(26682): 	at android.os.Handler.dispatchMessage(Handler.java:102)
02-05 23:23:15.882 E/AndroidRuntime(26682): 	at android.os.Looper.loop(Looper.java:154)
02-05 23:23:15.882 E/AndroidRuntime(26682): 	at android.app.ActivityThread.main(ActivityThread.java:6776)
02-05 23:23:15.882 E/AndroidRuntime(26682): 	at java.lang.reflect.Method.invoke(Native Method)
02-05 23:23:15.882 E/AndroidRuntime(26682): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
02-05 23:23:15.882 E/AndroidRuntime(26682): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
02-05 23:23:15.882 E/AndroidRuntime(26682): Caused by: android.view.InflateException: Binary XML file line #31: Binary XML file line #31: Error inflating class com.github.chrisbanes.photoview.PhotoView

The strange thing is that it suddenly started crashing, without any changes in code. I added 
multiDexEnabled true
since I saw in some previous posts that this might help, but it did not in my case.

**Comment by Jawnnypoo** [comment]
Check the guide here, https://developer.android.com/studio/build/multidex.html

Make sure you are calling `MultiDex.install(context)` properly

**Comment by Sandrichka22** [comment]
I've checked the guide and according to it, if your `minSdkVersion ` is 21 or higher (mine is 21), there is no need to call `MultiDex.install(context)` from the `Application` class. All you have to do is set `multiDexEnabled ` to `true ` in your module-level build.gradle file, which I do. What's interesting is that my crash occurs on a Samsung S8+ device, running Android 7.0. I will check how it behaves on other devices.

**Comment by Sandrichka22** [comment]
Just to correct myself, I previously mentioned that it suddenly started crashing, in fact it seems that it never worked on my Samsung S8+ device (running 7.0), I've tried with an older version of my application and the same error comes up. The older version does not have the `multiDexEnabled` set to `true`, though.

**Comment by Twenhimself** [comment]
Don't set optional settings of PhotoView in xml. for example, setting "src", do it in Activity.java might be good.

**Comment by qweenhool** [comment]
> Don't set optional settings of PhotoView in xml. for example, setting "src", do it in Activity.java might be good.

You saved my time, bro. It works!
